// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiraAilihX7KtWv4uvTSsS5Uu-S3_wKaU',
    appId: '1:977549736796:web:1e307ca6bcc311108d9f99',
    messagingSenderId: '977549736796',
    projectId: 'fitzee-c7e4d',
    authDomain: 'fitzee-c7e4d.firebaseapp.com',
    storageBucket: 'fitzee-c7e4d.firebasestorage.app',
    measurementId: 'G-V962565LNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO9mt7X9ZluhDS4CcE2ZWaWVkLOKoZsq0',
    appId: '1:977549736796:android:68082ca33748a1b18d9f99',
    messagingSenderId: '977549736796',
    projectId: 'fitzee-c7e4d',
    storageBucket: 'fitzee-c7e4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTa2PRmOScdouW3Sfnw7ExbMRG0zaRB4',
    appId: '1:977549736796:ios:b7024a78420ed3538d9f99',
    messagingSenderId: '977549736796',
    projectId: 'fitzee-c7e4d',
    storageBucket: 'fitzee-c7e4d.firebasestorage.app',
    androidClientId: '977549736796-gftknkg46go9hv0pbvemle363m5am7t6.apps.googleusercontent.com',
    iosClientId: '977549736796-frpugns2isj028n3kpv8cthmnp0qrtsl.apps.googleusercontent.com',
    iosBundleId: 'com.fitness.fitzee',
  );

}